from . import ru_appointment
from . import ru_lessons
from . import ru_main
from . import ru_main
from . import ru_portret
from . import start
from . import uz_appointment
from . import uz_lessons
from . import uz_main
from . import uz_portret
